### ISSUE TITLE
Not using .gff in STAR

### ISSUE THREAD

**Issue by FabianGrammes** [FabianGrammes/RNAseq-analysis#1]
```bash
#!/bin/bash

script=/mnt/users/fabig/cluster_pipelines/RNAseq-analysis/RNA_map.sh
fdir=/mnt/SeqData1/bovine/ullevaal_cow_rna_nov_2016/sample_pool
genome=/mnt/users/tikn/seqdata1/bovine/rna-seq/alignments_2_try/umd3.1
gtf=/mnt/users/tikn/seqdata1/bovine/reference/gtf/Bos_taurus.UMD3.1.86.gtf

bash $script -d $fdir -g $genome  -m master_sheet.txt -r short  --desc description_file.txt --execute no --copy no --gtf $gtf
```
The above produces the following STAR-command:
```bash
# Run STAR
STAR --limitGenomeGenerateRAM 62000000000 --genomeDir /mnt/users/tikn/seqdata1/bovine/rna-seq/alignments_2_try/umd3.1 --readFilesCommand zcat --readFilesIn $R1 $R2 --outFileNamePrefix $OUT --outSAMmode Full --outSAMtype BAM Unsorted --outSAMstrandField intronMotif --runThreadN 20 --readMatesLengthsIn NotEqual --outSAMattrRGline ID:$FILEBASE PL:illumina LB:$SAMPLE SM:$SAMPLE
```

No sign if the gtf..
Am I using the correct script? `script=/mnt/users/fabig/cluster_pipelines/RNAseq-analysis/RNA_map.sh`

**Comment by FabianGrammes** [comment]
Yes, correct so far the pipeline maps to the genome and uses the .gff just for counting. I actually thought to incorporate STAR using gff info ....

Do you want that ?

**Comment by timknut** [comment]
Yes, I guess. But not sure if it is an advantage? 
Maybe incorporating the automatic 2-pass feature as well? 
from section 8.1 here https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf 

My counts looked like this:

```
XLOC_007027     489
XLOC_007028     1251
XLOC_007029     290
XLOC_007030     71
XLOC_007031     30
XLOC_007032     69
```

So guessing I messed something up..

**Comment by FabianGrammes** [comment]
The 2-pass work flow is used when calling variants using the `SNP_call.sh` script. I think it would be overkill to run 2-pass mapping when counting reads. But I'll incorporate an option for STAR to use the .gff. 

P.S counts look OK to me how are the mapping stats ?

**Comment by timknut** [comment]
Stats seem fine. Meant the XLOC naming. Shouldn't it be proper gene IDs?

**Comment by FabianGrammes** [comment]
This solely depends on whats value is assigned in the `gene_id` attribute in your .gff file.

**Comment by FabianGrammes** [comment]
In conclusion it is easiest to incorporate gtf information when generating the genome index
